### ISSUE TITLE
Key Mapper was renamed to Input Remapper

### ISSUE THREAD

**Issue by sezanzeb** [sezanzeb/input-remapper#248]
This was done to avoid a naming conflict with a package called "keymapper" (without a dash) and because input-remapper is able map non-key inputs like joystick events to non-key events. The more broader term "input" suits this better therefore.

Discussion: https://github.com/sezanzeb/input-remapper/issues/218

**Comment by saikat0511** [comment]
[aur/key-mapper-git](https://aur.archlinux.org/packages/key-mapper-git/) should be merged into [aur/input-remapper-git](https://aur.archlinux.org/packages/input-remapper-git/) to avoid confusion.

**Comment by sezanzeb** [comment]
I have submitted a request to delete key-mapper-git.

Did I get that right that you are recommending to pull in the commits from aur/key-mapper-git into aur/input-remapper-git? The histories are unrelated, and what would be the benefit?

**Comment by saikat0511** [comment]
I meant a AUR merge request which carries over the votes and comments which will carry over the votes and comments from the old key-mapper-git package to the new input-remapper-git. It makes it easier for people to rediscover the package who are not keeping up with project news.

Since this is a project rename, merge request is preferred over deletion request

**Comment by sezanzeb** [comment]
Ah, yeah I didn't know this was a thing, I just went straight for the deletion. I made another request for merging, lets see what happens. Thanks
