### ISSUE TITLE
Remap modifiers when released only (keeping its function untouched)

### ISSUE THREAD

**Issue by jose1711** [sezanzeb/input-remapper#287]
Currently I find it impossible to map a modifier - e. g. Left Alt to a key if it's the only key pressed while keeping its original function (modifier) when combined with other keys.
Goal:
  - Left alt is "space" when pressed and released alone
  - Left alt + F2 still brings up execute dialog (in Gnome)

Configuration:
![obrázok](https://user-images.githubusercontent.com/1406222/152691673-fa22334a-e631-49d1-9726-6f14d9945158.png)

Result:
  - Left alt -> space works
  - Left + anything else - breaks

**Comment by jonasBoss** [comment]
It should work with `if_single(KEY_SPACE, LEFT_ALT)` 
https://github.com/sezanzeb/input-remapper/blob/main/readme/macros.md#if_single

**Comment by jose1711** [comment]
`if_single(key(KEY_SPACE), key(KEY_LEFTALT))`

Thank you, this works but only to an extent. In Gnome Alt-held, Tab-tapped, Alt-still held no longer brings the menu with active windows. "Alt-tabbing" between most recent windows still works though.

**Comment by sezanzeb** [comment]
`if_single(key(KEY_SPACE), hold(KEY_LEFTALT))` might work then

**Comment by jose1711** [comment]
> if_single(key(KEY_SPACE), hold(KEY_LEFTALT))

Thank you, that worked nicely. What if I want to map `Control L` + `Alt L` but only if pressed alone? `if_single` does not seem to be able to capture such events - it works for a single modifier, but not multiple ones.

**Comment by sezanzeb** [comment]
The issue is probably that while Control_L is pressed, all of the injected events are consumed by the environment to potentially trigger shortcuts. Like ctrl + a to select all.

Try mapping `Control L` to `Control L`, and add `key(Control_L)...` to your mapping. like:

![image](https://user-images.githubusercontent.com/28510156/152705257-f10df40a-d9d6-418a-9e61-21f8de77c534.png)

![image](https://user-images.githubusercontent.com/28510156/152705259-3f2400fd-ff5d-42f2-9ac5-d5174fa3fcd5.png)

This is a bit stupid as of now. In the future there will probably a `key_up` macro that properly releases the Control_L key before going into the macro.

The redundant control_l macro is needed at the moment to ensure the control event is sent to the "keyboard" uinput.

**Comment by jose1711** [comment]
Thank you, it's a bit complex but I works.
