### ISSUE TITLE
Ctrl+Right click

### ISSUE THREAD

**Issue by NikitaGolovaniuk** [sezanzeb/input-remapper#401]
Hi, i want to do: 
On click middle mouse button:
1. key_press L_CTRL (keyboard)
2. key_press BTN_RIGHT (mouse right click)
3. key_up L_CTRL (keyboard)
4. key_up BTN_RIGHT (mouse right click)
This looks pretty simple but looks like i can use only 1 device per time. If i choose mouse device from dropdown menu only part with right click work and vice versa

**Comment by sezanzeb** [comment]
Related discussion: https://github.com/sezanzeb/input-remapper/discussions/305

**Comment by Matafou** [comment]
Hi, I sneak in this conversation.
Even mapping some event to `key(h).key(BTN_LEFT)` does not work because these are two events on two different devices. Am I missing something?

**Comment by jonasBoss** [comment]
duplicate: #310

**Comment by Tesla-Tank** [comment]
Whats strange about this is that on the examples.md file, it shows a bind that has both mouse and keyboard controller (For mouse middle). Maybe it worked for an older version of input remapper or it was a mistake?
[https://github.com/sezanzeb/input-remapper/blob/main/readme/examples.md#combinations-spanning-multiple-devices](url)

**Comment by Matafou** [comment]
It definitely worked in key-mapper.

**Comment by sezanzeb** [comment]
I'll try to look into the proposed `with_device` macro soon

**Comment by sezanzeb** [comment]
In the past it worked a bit different. Instead of having well defined uinputs for keyboard, mouse, etc. there was one uinput that had all the capabilities it would need. This was a theoretical cause of certain other problems though, because if the capabilities are weird it wouldn't be recognized as a keyboard anymore and you wouldn't be able to write anything.

I think it should be possible to make a target that also contains mouse buttons, since this is pretty much how it has been in the past if I remember correctly. I need to look into that. It would be a "keyboard + mouse" target.

**Comment by sezanzeb** [comment]
I added a keyboard + mouse device and it worked well in
- gnome on wayland
- gnome on x11
- kde on x11

it's one the [keyboardplusmouse](https://github.com/sezanzeb/input-remapper/tree/keyboardplusmouse) branch

**Comment by sezanzeb** [comment]
it also worked in xfce4 on x11 in a vm. I'll merge it
