### ISSUE TITLE
Remapping CTRL_L + W to CTRL_R + Delete doesn't work

### ISSUE THREAD

**Issue by AlexMnrs** [sezanzeb/input-remapper#478]
Because I'm left-handed, on Windows I usually close browser tabs using (right)ctrl+del instead of ctrl+w.

In Input Remapper I tried these options:

1. Control_R + Delete
2. m(control_r, k(delete))
3. KEY_RIGHTCTRL + KEY_DELETE

None of them worked. Any suggestions? 

Many thanks!

**Comment by jonasBoss** [comment]
There are two issues I can think of: 

1. You are confusing input and output of your mapping the macro you need is `modify(KEY_LEFTCTRL, k(w))` (this will close the tab) and as a input you want to record `Control R + Delete` (this is what you press in order to trigger the macro).
2. Using modifier keys such as `Control R` as a mapping input can cause issues as described [here](https://github.com/sezanzeb/input-remapper/blob/main/readme/usage.md#combinations). On the beta branch this issue is solved and the macro from above should work just fine.

**Comment by AlexMnrs** [comment]
You were right! I was confusing input and output... What a shame. It works impeccably, I'm sorry.
