### ISSUE TITLE
Support short locale names

### ISSUE THREAD

**Issue by sezanzeb** [sezanzeb/input-remapper#488]
See https://github.com/sezanzeb/input-remapper/pull/487

the proposal is to symlink ru to ru_RU

Idk if this can be done in https://github.com/sezanzeb/input-remapper/blob/main/setup.py, or if this should be done in the AUR and the .deb file scripts.

**Comment by sezanzeb** [comment]
maybe it is possible to symlink po/ru to po/ru_RU in the repo already, and push that symlink to github

**Comment by yngmjgsd** [comment]
I've just found out there is the same behavior in KDE for some other locales. For example, **sk_SK** translation is not loaded on KDE if it is set up the same way:

![image](https://user-images.githubusercontent.com/115377018/195380084-c17b942b-9882-4409-93c3-87aa2b8e31bb.png)

Even worse - different translation is loaded for policy-kit dialog (**ru**) since **sk_SK** was not detected and it fallback to another available (which is **ru**). I guess the same must be done for **sk_SK** translation (a symlink solution).

I tested it for the same distros and even for Debian 11. I guess it must be true for every KDE Plasma 5 installation with the same settings.
