### ISSUE TITLE
Feature request: mouse scroll wheel speed

### ISSUE THREAD

**Issue by izzylaif** [sezanzeb/input-remapper#492]
Surprisingly enough, none of the popula DEs (exept KDE and LXQT) allow to change the amount of lines a mouse wheel scrolls per step.
The xinput method and imwheel are very flawed.

How about adding such setting to input-remapper?
A specific feature, not remapping of scroll wheel which already works.

**Comment by jonasBoss** [comment]
duplicate: #99 
the issue is not yet solved, but we are working on [this](https://github.com/sezanzeb/input-remapper/issues/99#issuecomment-1152776531) solution.

It is not going to be a "specific feature" but a general remapping of mouse wheel to mouse wheel which allows you to change the sensitivity in the process.
