### ISSUE TITLE
Consistent OS crashing after installing on Ubuntu 22.04

### ISSUE THREAD

**Issue by mxgrey** [sezanzeb/input-remapper#518]
First, thanks for making this tool. It's amazing and I look forward to using it extensively with my mouse that has way too many buttons on it. I don't know if an MMORPG mouse can improve software development workflow, but I certainly intend to find out.

However, at the moment it seems that installing `input-remapper` on my Ubuntu 22.04 machine causes the whole OS to crash. Here's a quick rundown of what I experienced beginning from last night:

1. Installed `input-remapper` and its dependencies using `$ sudo apt install input-remapper`
2. Successfully used `input-remapper-gtk` to customize some buttons on my Logitech G600
3. Everything worked great for several hours
4. Restarted my computer, and then the whole OS crashed mysteriously after being on for ~2 minutes
5. Restarted my computer several more times, thinking Slack or Firefox was causing my whole OS to crash, but eventually I realized that just logging in and doing nothing would still lead to a crash after ~2 minutes
6. Logged in to terminal mode and investigated. The OS doesn't seem to ever crash in terminal mode. While in terminal mode I could uninstall `input-remapper`.
7. When `input-remapper` and all its dependencies are uninstalled, the crash stops happening.
8. Reinstalling `input-remapper` consistently causes the crashes to resume. Deleting `~/.config/input-remapper` does not help. In one instance, the OS crashed *while installing* `input-remapper`.

[Here's a gist containing the log from one of the crashes](https://gist.github.com/mxgrey/7217f8c2a72111c77db4606c8acc4b3b). One entry that stands out to me is this one:
```
Oct 28 14:11:53 2B kernel: [   71.475360] Out of memory: Killed process 1108 (input-remapper-) total-vm:34098332kB, anon-rss:31595860kB, file-rss:280kB, shmem-rss:0kB, UID:0 pgtables:66628kB oom_score_adj:0
```

My machine has 32GB of memory, so It looks like for some reason `input-remapper` starts trying to consume all the RAM while starting up. In general I've seen that my OS often crashes whenever the RAM is fully consumed, so I think it's safe to assume a memory usage explosion is the key issue here.

Please let me know if there are any further steps I can take to help debug the issue. I'd very much like to get this tool working for me.

**Comment by sezanzeb** [comment]
hey,

please try installing from the `beta` branch. There have been a lot of changes, so there is a chance that the memory leak is not present there anymore.

If that doesn't help, run `sudo systemctl disable input-remapper` after the installation and boot again. It won't autostart then. Is the os still crashing?

If you start `sudo input-remapper-service` in a console, does ram start to fill up? Can you see in e.g. `htop` how input-remappers ram usage goes up?

Delete `/usr/lib/udev/rules.d/99-input-remapper.rules`, which will prevent udev from talking to input-remapper. Does that prevent the ram issue?

---

A side note on the kernel oom:

Since this only happens when input-remapper is installed, it is probably safe to assume that input-remapper is somehow filling the memory up. However, If I remember correctly the kernel oom killer is known to be really bad and kills those processes that were the last ones to allocate memory, instead of the ones who have the majority of the ram occupied. Which is why https://github.com/rfjakob/earlyoom exists. If you really want to make sure it is actually input-remapper that occupies all of the memory, dump memory usages to a file and read it after it crashes.

**Comment by mxgrey** [comment]
Thanks for the help!

After uninstalling the apt packages and installing the beta branch the tool is working, and so far there have been no crashes, even after several restarts :tada:

**Comment by sezanzeb** [comment]
ah, great!
