### ISSUE TITLE
Conflicting with KDE `Invert Scrolling` flags

### ISSUE THREAD

**Issue by adhiemsumitro** [sezanzeb/input-remapper#691]
I'm currently running Fedora 38 with KDE Plasma 5.27.4 on Wayland. After activating the mouse's Invert Scrolling feature and rebinding an extra button to zoom in and out, everything was working great. 
However, when I later tried using Input-Remapper to remap my mouse's middle button to Invert colors, I encountered an issue. Although the remapping worked flawlessly, it caused the mouse scrolling to revert back to normal, undoing the Invert Scrolling feature. Fortunately, the zoom-in and zoom-out button assignments remained functional. 
I confirmed that the Input-Remapper was the cause by pausing its activation and testing the mouse scrolling.

**Comment by jonasBoss** [comment]
InputRemapper creates a clone of the mouse whenever a preset for the mouse is Active. For KDE this probably looks like the original mouse disappeared and a new one is plugged in. I am not sure how KDE-Plasma handles this situation possibly a bug with KDE-Plasma.

But you can workaround this issue by creating a mapping for the `Wheel` -> `Wheel`. Set the deadzone to 0 and the gain to -1. You also want a mapping for `Wheel HI RES` -> `disable` if that appears in the input recording.
you may need to use the `Advanced` input menu in order to seperate `Wheel` and `Wheel HI RES`.
![Screenshot_20230606_155956](https://github.com/sezanzeb/input-remapper/assets/31804124/a3083ac8-a98c-4d72-8e30-2752ae3f40ff)
![Screenshot_20230606_160014](https://github.com/sezanzeb/input-remapper/assets/31804124/4948a5b7-9959-4d5b-990a-65abfd9d2031)

**Comment by sezanzeb** [comment]
Worked fine for me:

```
Operating System: Kubuntu 23.04
KDE Plasma Version: 5.27.4
KDE Frameworks Version: 5.104.0
Qt Version: 5.15.8
Kernel Version: 6.2.0-27-generic (64-bit)
Graphics Platform: X11
```

Closing because there is also a workaround, and this is probably not input-remappers bug.

**Comment by FinnWoelm** [comment]
Just FYI for anyone coming to this issue because they remapped some buttons for their touchpad: I was not able to map scrolling using input remapper (probably because it's not a real button on a touchpad). But the remapped touchpad did show up in the KDE settings (see device dropdown at the top) and I was able to invert the scroll direction there:

![image](https://github.com/sezanzeb/input-remapper/assets/7606194/88abd01f-d739-4c34-9646-aa0562f784f5)

```
KDE Plasma Version: 5.27.10
KDE Frameworks Version: 5.114.0
Qt Version: 5.15.12
Graphics Platform: Wayland
```
