### ISSUE TITLE
Correct device not listed.

### ISSUE THREAD

**Issue by 1094** [sezanzeb/input-remapper#775]
`AT Translated Set 2 keyboard` is one of the default devices; however, when I chose that device, it doesn't recognize that I'm pressing any keys. If I click `Apply` I get `The device was not grabbed.` After doing some digging, I found `sudo evtest` and according to that, my laptop's keyboard is actually `PRiMAX HP OMEN 16 KBM Keypad`. What I haven't been able to find is a way to add that keyboard to the list of devices I see when I open the program.  Can you help me with that?

**Comment by 1094** [comment]
> When clicking record, right?

Yes. When clicking record. 

If I select my USB keyboard, it's shows up with the right name `Keychron Keychron Q9` but is listed as a mouse. I can set input and output, but when I apply it, the device is not grabbed.   

But if I select `PRiMAX HP OMEN 16 KBM Mouse`, everything seems to work fine. It let me set the input and output and it's saving and remapping the keys.

It wouldn't have occurred to me to try a different device. Thanks.

But now I have another question:

**Comment by sezanzeb** [comment]
Interesting.

in `sudo evtest` it will show you the device capabilities, below `Supported events:`. This is what input-remapper (and all other tools as far as I know) have to use to figure out the kind of device. If input-remapper is mixing up things, it might be because the capabilities are weird or something.

But everything definitely works now? And `PRiMAX HP OMEN 16 KBM Mouse` is listed as a keyboard in input-remapper?

**Comment by 1094** [comment]
Yup, everything seems to working now. I'll go ahead and close this. Thanks again for the suggestion.
