### ISSUE TITLE
Store Current Mouse Position as a Variable

### ISSUE THREAD

**Issue by itsDevBlaze** [sezanzeb/input-remapper#803]
Is there a way to store your current mouse position as a variable? My use case is storing the Y location of the mouse, teleporting it to a specified Y location, left-clicking, and then teleporting it back to the stored variable.

I can currently move the mouse anywhere relative to its current location using "mouse(direction, speed)", which can accomplish moving the mouse to the top of the display by setting "speed" to an absurd amount, and then using the same macro string again to move it down to where I need it to click at. The only issue is that I then can't move the mouse back to its original Y position - only to a specified location.

**Comment by sezanzeb** [comment]
mouse movements are always relative. The current cursor position is probably only known to the desktop environment, or X11 or whatever. This is problematic, because making input-remapper interface correctly with all desktop environments is difficult, and might even be impossible given the current architecture. Macros are basically running as the root user, and they have therefore no knowledge of the users desktop session.
