### ISSUE TITLE
Module missing

### ISSUE THREAD

**Issue by Axilotl17** [sezanzeb/input-remapper#895]
`axilotl@tiramisu ~ [1]> sudo pkill -f input-remapper && input-remapper-gtk -d
Traceback (most recent call last):
  File "/usr/bin/input-remapper-gtk", line 38, in <module>
    from inputremapper.gui.gettext import _, LOCALE_DIR
ModuleNotFoundError: No module named 'inputremapper'
`

Can't even run suggested command. reinstalled several times, to no effect. Same error when running `input-remapper-control`.

Using Arch, `input-remapper-git` on the AUR.

**Comment by Virass** [comment]
I have the same problem. Manjaro, gnome, wayland.

![image](https://github.com/sezanzeb/input-remapper/assets/24947782/5596129a-6f68-476a-b82c-7b0da00a689b)

**Comment by alexisju** [comment]
Same here (Archlinux/AUR too). Was working before it doesn't :-)

**Comment by leonardofmoura** [comment]
Same thing here: Arch Linux with Wayland. Using is `input-remapper-git`

![image](https://github.com/sezanzeb/input-remapper/assets/38780723/d0c70805-de77-409b-b9dc-0606238aaa91)

**Comment by nicfontaine** [comment]
Same. Manjaro, Gnome, Wayland
![image](https://github.com/sezanzeb/input-remapper/assets/10342477/e07a134e-0090-4570-a751-09b1eeb51c4f)

**Comment by Pablokiryu** [comment]
i got it to run as root, using sudo, but without it i get :
`Gtk-Message: 11:54:18.672: Failed to load module "appmenu-gtk-module"
input-remapper-gtk 2.0.1 f5151aab27ae0e7d8b1f0c80ce92a718e3a86e71 https://github.com/sezanzeb/input-remapper
python-evdev 1.7.0
pkexec must be setuid root
ERROR: Failed to pkexec the reader-service, code 32512
`

**Comment by meinmycomfycorner** [comment]
> systemctl enable input-remapper
# no error

> systemctl start input-remapper

Job for input-remapper.service failed because the control process exited with error code.
See "systemctl status input-remapper.service" and "journalctl -xeu input-remapper.service" for details.

> journalctl -xeu input-remapper.service

Jun 17 11:57:49 input-remapper-service[29694]: ModuleNotFoundError: No module named 'inputremapper'
Jun 17 11:57:49 systemd[1]: input-remapper.service: Main process exited, code=exited, status=1/FAILURE
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: https://forum.manjaro.org/c/support
░░ 
░░ An ExecStart= process belonging to unit input-remapper.service has exited.
░░ 
░░ The process' exit code is 'exited' and its exit status is 1.
Jun 17 11:57:49 systemd[1]: input-remapper.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://forum.manjaro.org/c/support
░░ 
░░ The unit input-remapper.service has entered the 'failed' state with result 'exit-code'.
Jun 17 11:57:49 systemd[1]: Failed to start Service to inject keycodes without the GUI application.
░░ Subject: A start job for unit input-remapper.service has failed
░░ Defined-By: systemd
░░ Support: https://forum.manjaro.org/c/support
░░ 
░░ A start job for unit input-remapper.service has finished with a failure.
░░ 
░░ The job identifier is 3805 and the job result is failed.

####
# I've tried yay, manually w/ pip and pacman via git clone installations.
# System:
> uname -r
6.9.3-3-MANJARO

> python -VV                                                     
Python 3.11.9 (main, Apr 19 2024, 18:35:38) [GCC 13.2.1 20230801]

**Comment by archerindigo** [comment]
I have the same issue on Manjaro Gnome

```
× input-remapper.service - Service to inject keycodes without the GUI application
     Loaded: loaded (/usr/lib/systemd/system/input-remapper.service; enabled; preset: disabled)
     Active: failed (Result: exit-code) since Tue 2024-06-25 19:01:09 EDT; 20s ago
    Process: 21279 ExecStart=/usr/bin/input-remapper-service (code=exited, status=1/FAILURE)
   Main PID: 21279 (code=exited, status=1/FAILURE)
        CPU: 111ms

Jun 25 19:01:08 terry-manjaro systemd[1]: Starting Service to inject keycodes without the GUI application...
Jun 25 19:01:09 terry-manjaro input-remapper-service[21279]: Traceback (most recent call last):
Jun 25 19:01:09 terry-manjaro input-remapper-service[21279]:   File "/usr/bin/input-remapper-service", line 28, in <module>
Jun 25 19:01:09 terry-manjaro input-remapper-service[21279]:     from inputremapper.logger import update_verbosity, log_info
Jun 25 19:01:09 terry-manjaro input-remapper-service[21279]: ModuleNotFoundError: No module named 'inputremapper'
Jun 25 19:01:09 terry-manjaro systemd[1]: input-remapper.service: Main process exited, code=exited, status=1/FAILURE
Jun 25 19:01:09 terry-manjaro systemd[1]: input-remapper.service: Failed with result 'exit-code'.
Jun 25 19:01:09 terry-manjaro systemd[1]: Failed to start Service to inject keycodes without the GUI application.
```

**Comment by archerindigo** [comment]
Resolved. You just need to rebuild the whole package.

**Comment by Axilotl17** [comment]
Rebuilding doesn't work for me.

**Comment by nicfontaine** [comment]
I reinstalled through gnome's Add/Remove Software, rather than pacman, and version `2.0.1r10.g7586ad99-1` runs fine for me in Gnome 46.4 👍🏿

**Comment by pauloday** [comment]
I also had this issue on Arch. For me it was because I had a pyenv version other than the system one set on install. It looks like the install script respects the pyenv `PATH`, but when you run the script as a command with a shebang it's not using the pyenv path. So it can't find any of the input-remapper files. To solve it I uninstalled, ran `pyenv global system` to reset the pyenv version, then reinstalled, and it works.

This seems like a bug with either the installer or the imports, they don't agree on whether to use the pyenv `PATH`.

**Comment by sezanzeb** [comment]
To debug problems with imports:

1. Beware, that input-remapper starts/needs some privileged processes, and therefore needs system-wide installed packages.
2. Do `find /usr -name inputremapper` to find possibly multiple python installations, depending on python paths and stuff. It is most likely desireable to only have one installation.
3. You can do something like `import sys; print(sys.path)` to figure out your python paths, that might help you.
4. If you are able to import inputremapper in some cases, you can also try `import inputremapper; print(inputremapper.__file__)` to figure out from where you are currently importing inputremapper

Apart from that, input-remapper hasn't been using the recommended shebang. This will be fixed in https://github.com/sezanzeb/input-remapper/pull/992

**Comment by Turab** [comment]
> Resolved. You just need to rebuild the whole package.

For the Googler:

Every now and then Python gets updated, its path changes and input-remapper could break with this error again. here is what you need to do in that case:

- Remove the package input-remapper you had installed
- Remove the remnants like this:
```bash
sudo find /usr/lib/python3.* -name "*inputremapper*" -exec rm -rf {} +
sudo find /usr/lib/python3.* -name "*input-remapper*" -exec rm -rf {} +
sudo rm -rf /usr/share/input-remapper*
sudo rm -rf ~/.cache/input-remapper*
```
- Then "rebuild" it from git package:
```bash
yay -Syu --rebuild input-remapper-git # or paru if you have that instead
```
