### ISSUE TITLE
How do I associate scroll wheel with Ctrl-+ and Ctrl-- ?

### ISSUE THREAD

**Issue by nelson777** [sezanzeb/input-remapper#969]
I would like to use scroll wheel to the "make everything bigger/smaller" functions, traditionally associated with "Ctrl and +" and "Ctrl and -" keys. 

How I do this in input-remapper ? AFAIK there's no symbol for "+" key. I can only see a symbol called "minus". At least there's no symbol associated with this key in `input-remapper-control --symbol-names` list.

I've tried the following sequences:

Control_L + +
Control_L + -
Control_L + wheel(up, 10)
Control_L + wheel(down, 10)
Control_L + minus
Control_L + plusminus

None of them worked. The scrollwheel just rolls the page as normal.

**Comment by jonasBoss** [comment]
you can figure out the exact key-codes by running `sudo evtest` select your keyboard, and watch which key-codes get send when you press the desired combination on your keyboard.

The plus and minus on the keypad are usually `KEY_KPPLUS` and `KEY_KPMINUS` and on a German layout they seem to be `KEY_RIGHTBRACE` and `KEY_SLASH` (depends on your layout settings).

So you probably want `Wheel Down -> Control_L+KEY_KPMINUS` and `Wheel Up -> Control_L+KEY_KPPLUS` 

It is likely that you will see Scrolling and zooming at the same Time, that is due to your mouse sending two events at the same time for scrolling `REL_WHEEL` events and `REL_WHEEL_HI_RES` events, and only one of them is suppressed by your mapping. That case you want to create another mapping `Wheel -> disable`

**Comment by nelson777** [comment]
Thanks for the help.

I tried that, but it didn't work. My device is a ProtoArc EM03 trackball.

I checked evtest for the code keys and they are indeed `KEY_KPPLUS` and `KEY_KPMINUS`. 

About the 2 events, the case is that when I record the up and down scroll button, I get these events: `Wheel Down + Wheel HI RES -`  and `Wheel Up + Wheel HI RES +`. So AFAIU those 2 events should be matched already.

I don't know how I could add only one of them as both are recognized on record automatically. Also I don't know how I could add an input to `Wheel -> disable` as I don't have any means to add an event by the name. 

I tried to edit presets file in `/home/myuser/.config/input-remapper-2/presets/Nordic 2.4G Wireless Receiver` but there's a hash there I don't know how to generate. 

so some questions: 
1 - should I create only `Wheel Up/Down` events without `Wheel HI RES +/-` events ? how would I do that ?
2 - how to add `Wheel -> disable` event ?
3 - if I have to directly edit the configuration file how do I generate the hash ? 

Thanks.

**Comment by jonasBoss** [comment]
1. you can try to just record the wheel again in a new mapping, it should say `Wheel Up` or `Wheel Down`. Then go to "Advanced" and check the "Use as analog" toggel.
![Bildschirmfoto_20241010_232347](https://github.com/user-attachments/assets/bfcaac1a-a53a-4f12-9818-fe3c05024e0e)

If that does not work, you can go to the "Advanced" settings of the `Wheel Up + Wheel HI RES +` mapping and remove the `Wheel Up` input first. Do the same for `Wheel Down + Wheel HI RES -`.

2. The hash is unique to the input-device make and model, but each input-device might have multiple hashes. If a mouse has extra keyboard buttons, it will probably have two hashes, one for all the mouse functionality and one for the keyboard functionality. Because you only care about the mouse functionality, you can just copy the hash that was already recorded with your `Wheel Up + Wheel HI RES +` mapping. In most cases, it is also fine to remove the hash.


Probably the most reliable way to do your mapping would be to create 3 mappings:
 1. `Wheel HI RES +` -> zoom in (not `Wheel Up + Wheel HI RES +`)
 2. `Wheel HI RES -` -> zoom out
 3. `Wheel` -> disable

The preset (with _for you_ wrong `origin_hash` ):
```json
[
    {
        "input_combination": [
            {
                "type": 2,
                "code": 11,
                "origin_hash": "4a7e8e47ac053eac4fb9d67b78df2a8e",
                "analog_threshold": 1
            }
        ],
        "target_uinput": "keyboard",
        "output_symbol": "Control_L+KEY_KPPLUS",
        "mapping_type": "key_macro"
    },
    {
        "input_combination": [
            {
                "type": 2,
                "code": 11,
                "origin_hash": "4a7e8e47ac053eac4fb9d67b78df2a8e",
                "analog_threshold": -1
            }
        ],
        "target_uinput": "keyboard",
        "output_symbol": "Control_L+KEY_KPMINUS",
        "mapping_type": "key_macro"
    },
    {
        "input_combination": [
            {
                "type": 2,
                "code": 8,
                "origin_hash": "4a7e8e47ac053eac4fb9d67b78df2a8e"
            }
        ],
        "target_uinput": "keyboard",
        "output_symbol": "disable",
        "mapping_type": "key_macro"
    }
]
```

**Comment by nelson777** [comment]
It worked perfectly. Thanks.

Just for clarify if someone finds this issue, the correct configuration is this:

1 - Configure Wheel disabled: 
    - add a new mapping
    - record any scroll wheel move.
    - press "Advanced" button.
    - remove Wheel Up/Down event leaving only HI RES +/- event.
    - Check `use as analog`.
    - put `disable` in the output.

2 - Configure Wheel Up:
    - add a new mapping
    - record Wheel up event. It will apear as `Wheel Up + Wheel HI RES +`.
    - press "Advanced button" .
    - there will be 2 events:  `Wheel Up` and `Wheel HI RES +`.
    - select `Wheel Up` and press "Remove this input" button.
    - put `Control_L + KEY_KPPLUS` in the output field.

3- Configure Wheel Down:
    - same procedure as above substituting the event names by `Wheel Down` and `Wheel HI RES -` and `Control_L + KEY_KPMINUS` for the output field.

Hope this helps someone. Again thanks @jonasBoss

**Comment by nelson777** [comment]
Issue resolved. Closing.
